---
apiVersion: spaces.tanzu.vmware.com/v1alpha1
kind: Profile
metadata:
  name: ${PROFILE}
spec:
  traits:
  - name: egress.tanzu.vmware.com
    alias: egress
  - name: multicloud-cert-manager.tanzu.vmware.com
    alias: multicloud-cert-manager
  - name: multicloud-ingress.tanzu.vmware.com
    alias: multicloud-ingress.tanzu.vmware.com
    values:
      inline:
        multicloud-ingress.tanzu.vmware.com:
          name: default-gateway
          domain: ${FQDN}
          gslb:
            authentication:
              credentialRef: ${GSLB_CRED_REF}
            dns:
              zoneId: ${ZONE_ID}
          listenerTemplates:
          - namePrefix: https-
            port: 443
            protocol: HTTPS
            tls:
              secretRef: prod-certs
          - namePrefix: http-
            port: 80
            protocol: HTTP
            tls:
              secretRef: ""